[package]
name = "wluma"
version = "2.0.0"
authors = ["Maxim Baz"]
edition = "2018"

[dependencies]
vulkano = "0.25.0"
wayland-client = "0.29.0"
wayland-protocols = { version = "0.29.0", features = ["client", "unstable_protocols"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
dirs = "3.0"
toml = { git = "https://github.com/johansglock/toml-rs" }
chrono = "0.4"
ash = "0.33"
itertools = "0.10"
nalgebra = "0.29"
xdg = "2.2"
mockall = "0.10"
