display = "wayland"

[screen_contents]
capturer = "wlroots"
processor = "vulkan"

[als.iio]
path = "/sys/bus/iio/devices"

# [als.time]
# hour_to_lux = { 10 = 1, 13 = 2, 16 = 1, 20 = 0 }

# [als.none]

[output.backlight.eDP-1]
path = "/sys/class/backlight/intel_backlight"
use_contents = true

# [output.ddcutil.DP-1]
# display = 1
# use_contents = false

[keyboard.backlight.dell]
path = "/sys/bus/platform/devices/dell-laptop/leds/dell::kbd_backlight"

# [keyboard.backlight.thinkpad]
# path = "/sys/bus/platform/devices/thinkpad_acpi/leds/tpacpi::kbd_backlight"
